### ISSUE TITLE
skdh.gait.GaitLumbar() frequency setting error

### ISSUE THREAD

**Issue by HowonRyu** [pfizer-opensource/scikit-digital-health#130]
<img width="1325" alt="image" src="https://github.com/PfizerRD/scikit-digital-health/assets/46797129/d5cde937-68a6-4349-a9a0-0815905f31aa">

I was trying the above, but I encountered the following error:

<img width="1217" alt="image" src="https://github.com/PfizerRD/scikit-digital-health/assets/46797129/1cb64023-a7b1-4f6c-aff8-156614b343b3">

My data has 31.25Hz frequency, so I am not sure why it registers it as having frequency 0.03Hz. Is there anyway I can fix this?

Alternatively I have tried the following:

<img width="1322" alt="image" src="https://github.com/PfizerRD/scikit-digital-health/assets/46797129/d1a55c1c-05f0-472f-8cb4-e80b5580e9db">

but for some reason the jupyter notebook kernel crashed.

How would I resolve this?

**Comment by LukasAdamowicz** [comment]
Without seeing the actual error its hard to tell why exactly for either dataset

For the first error, (frequency error), this is possibly a conversion error, where SKDH requires units of "seconds" but you are passing in "ms". 

As for the kernel error, without seeing any logs or data its hard to tell. Its possibly also caused by the units as above, but hard to tell. 

If unit conversion does not solve the issue, and if you want me to try to replicate please reach out via email if you are able to share sample data that causes this issue.
